name: Tailnet Link Up
description: Connect your GitHub Actions workflow to Tailscale
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  authkey:
    description: A Tailscale auth key or OAuth client secret.
    required: true
  tags:
    description: |
      A comma-separated list of tags to apply to nodes authenticated by this action.
    required: false
  extra-args:
    description: Optional additional arguments to `tailscale up`.
    required: false
  tailscaled-extra-args:
    description: Optional additional arguments to `tailscaled`.
    required: false
  hostname:
    description: A fixed machine name.
    required: false


runs:
  using: composite
  steps:
    - name: Checkout celsiusnarhwal/tailnet-link
      uses: actions/checkout@v4

    - name: Connect to Tailscale
      uses: ./celsiusnarhwal/tailnet-link/action.yml
      with:
        authkey: ${{ inputs.authkey }}
        tags: ${{ inputs.tags }}
        extra-args: ${{ inputs.extra-args }}
        tailscaled-extra-args: ${{ inputs.tailscaled-extra-args }}
        hostname: ${{ inputs.hostname }}
      env:
        _TAILNET_LINK_DO_NOT_DISCONNECT: 1