name: Tailnet Link
description: Connect your GitHub Action workflow to Tailscale
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  authkey:
    description: A Tailscale auth key or OAuth client secret.
    required: true
  tags:
    description: |
      A comma-separated list of tags to apply to nodes authenticated by this action.
    required: false
  version:
    description: The version of Tailscale to use.
    required: true
    default: latest
  extra-args:
    description: Optional additional arguments to `tailscale up`.
    required: false
  tailscaled-extra-args:
    description: Optional additional arguments to `tailscaled`.
    required: false
  hostname:
    description: A fixed machine name.
    required: false

runs:
  using: composite
  steps:
    - name: Set Up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Setup
      shell: python
      run: import os, uuid; print(f"VENV={uuid.uuid4().hex}", file=open(os.getenv("GITHUB_ENV"), "a"))

    - name: Handle Inputs
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          pipx install pew
          pew new ${{ env.VENV }} -d -r ${{ github.action_path}}/requirements.txt
          pew in ${{ env.VENV }} python ${{ github.action_path }}/inputs.py
        post: pew rm ${{ env.VENV }}
        shell: bash
      env:
        TS_AUTHKEY: ${{ inputs.authkey }}
        TS_TAGS: ${{ inputs.tags }}
        TS_EXTRA_ARGS: ${{ inputs.extra-args }}
        TS_TAILSCALED_EXTRA_ARGS: ${{ inputs.tailscaled-extra-args }}
        TS_HOSTNAME: ${{ inputs.hostname }}

    - name: Install Tailscale (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: curl -fsSL https://tailscale.com/install.sh | sh

    - name: Install Tailscale (macoS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: brew install tailscale

    - name: Install Tailscale (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: choco install tailscale -y

    - name: Start tailscaled (macOS and Linux)
      if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: sudo tailscaled ${{ env.TAILSCALED_ARGS }} &

    - name: Connect to Tailscale (macOS and Linux)
      if: ${{ runner.os != 'Windows' }}
      uses: gacts/run-and-post-run@v1
      with:
        run: sudo tailscale up ${{ env.TAILSCALE_ARGS }}
        post: sudo tailscale logout
        shell: bash

    - name: Connect to Tailscale (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: gacts/run-and-post-run@v1
      with:
        run: ./tailscale.exe up ${{ env.TAILSCALE_ARGS }}
        post: ./tailscale.exe logout
        shell: bash
        working-directory: "C:/Program Files/Tailscale"
