name: Tailnet Link Down
description: Disconnect your GitHub Actions workflow from Tailscale
branding:
  icon: arrow-right-circle
  color: gray-dark


runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v3

    - name: Install tscmd
      shell: bash
      run: uv tool install git+https://github.com/celsiusnarhwal/tailnet-link/#subdirectory=tscmd

    - name: Disconnect from Tailscale
      shell: bash
      run: tscmd logout

    - name: Uninstall tscmd
      shell: bash
      run: uv tool uninstall tscmd