name: Tailnet Link Down
description: Disconnect your GitHub Actions workflow from Tailscale
branding:
  icon: arrow-right-circle
  color: gray-dark


runs:
  using: composite
  steps:
    - name: Disconnect from Tailscale
      shell: bash
      run: tscmd logout