on:
  workflow_dispatch:
    inputs:
      authkey:
        description: "authkey"
        required: false


jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Connect to Tailscale
        uses: celsiusnarhwal/tailnet-link@main
        with:
          authkey: ${{ inputs.authkey }}
          tags: tag:github-actions
          extra-args: --accept-routes --accept-dns

      - name: Connect to Tailscale (macOS and Linux)
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: sudo tailscale ip

      - name: Connect to Tailscale (Windows)
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: ./tailscale.exe ip
        working-directory: 'C:/Program Files/Tailscale'
